using ChangeTrace.Configuration.Discovery;
using ChangeTrace.Core.Events;
using ChangeTrace.Rendering.Commands;
using ChangeTrace.Rendering.Interfaces;
using Microsoft.Extensions.DependencyInjection;

namespace ChangeTrace.Rendering.Translators;

/// <summary>
/// Orchestrates pipeline of <see cref="IEventTranslator"/> instances to convert <see cref="TraceEvent"/> objects
/// into <see cref="RenderCommand"/> sequences for the visualization system.
/// </summary>
/// <remarks>
/// <para>
/// Translators are registered with numeric priority. Lower numbers run earlier. Multiple translators can handle same event.
/// The pipeline always includes fallback translator as the last step to ensure no event is left untranslated.
/// </para>
/// <para>
/// Builtin translators include:
/// <list type="bullet">
/// <item><see cref="CommitTranslator"/> – translates commit events.</item>
/// <item><see cref="BranchTranslator"/> – translates branch events.</item>
/// <item><see cref="PullRequestTranslator"/> – translates pull request events.</item>
/// <item><see cref="FallbackTranslator"/> – catch-all for any unmatched events.</item>
/// </list>
/// </para>
/// </remarks>
[AutoRegister(ServiceLifetime.Singleton)]
internal sealed class TranslationPipeline : ITranslationPipeline
{
    private readonly List<(int Priority, IEventTranslator Translator)> _translators = [];

    /// <summary>
    /// Creates default <see cref="TranslationPipeline"/> pre populated with all builtin translators.
    /// </summary>
    /// <returns>A <see cref="TranslationPipeline"/> instance with default translators registered.</returns>
    internal static TranslationPipeline Default()
    {
        var p = new TranslationPipeline();
        p.Register(new CommitTranslator(), priority: 10);
        p.Register(new BranchTranslator(), priority: 10);
        p.Register(new PullRequestTranslator(), priority: 10);
        p.Register(new FallbackTranslator(), priority: int.MaxValue);  // always last
        return p;
    }

    /// <summary>
    /// Registers new <see cref="IEventTranslator"/> in pipeline.
    /// </summary>
    /// <param name="translator">The translator to register.</param>
    /// <param name="priority">
    /// Numeric priority of the translator. Lower numbers are executed earlier. Defaults to 10.
    /// Multiple translators can match the same event; order is determined first by priority, then registration order.
    /// </param>
    public void Register(IEventTranslator translator, int priority = 10)
    {
        _translators.Add((priority, translator));
        _translators.Sort((a, b) => a.Priority.CompareTo(b.Priority));
    }

    /// <summary>
    /// Translates <see cref="TraceEvent"/> into sequence of <see cref="RenderCommand"/> objects.
    /// </summary>
    /// <param name="evt">The event to translate.</param>
    /// <returns>
    /// A readonly list of render commands generated by first matching translator(s).
    /// The fallback translator always runs last if no other translator handled event.
    /// </returns>
    public IReadOnlyList<RenderCommand> Translate(TraceEvent evt)
    {
        var commands = new List<RenderCommand>();

        foreach (var (_, translator) in _translators)
        {
            if (!translator.CanHandle(evt)) continue;
            commands.AddRange(translator.Translate(evt));
            if (translator is not FallbackTranslator) break;
        }

        return commands;
    }
}