using ChangeTrace.Core.Events;
using ChangeTrace.Rendering.Commands;

namespace ChangeTrace.Rendering.Interfaces;

/// <summary>
/// Defines pipeline that manages multiple <see cref="IEventTranslator"/>s and translates events into render commands.
/// </summary>
/// <remarks>
/// Translators can be registered with priority. Lower priority values run earlier. 
/// Multiple translators may match same event, but pipeline controls execution order.
/// </remarks>
internal interface ITranslationPipeline
{
    /// <summary>
    /// Registers translator with pipeline.
    /// </summary>
    /// <param name="translator">The <see cref="IEventTranslator"/> to register.</param>
    /// <param name="priority">
    /// The execution priority of the translator. Lower values are executed earlier.
    /// Defaults to 10.
    /// </param>
    void Register(IEventTranslator translator, int priority = 10);
    
    /// <summary>
    /// Translates single <see cref="TraceEvent"/> into one or more <see cref="RenderCommand"/>s
    /// using registered translators.
    /// </summary>
    /// <param name="evt">The event to translate.</param>
    /// <returns>
    /// An ordered list of <see cref="RenderCommand"/> objects generated by pipeline.
    /// </returns>
    IReadOnlyList<RenderCommand> Translate(TraceEvent evt);
}